### ISSUE TITLE
Feat : 테이블 redis 필드 추가 요청

### ISSUE THREAD

**Issue by anjm1020** [BiBimBapClub/bitpay_server#1]
현재 Table 상태가 redis에서 관리되는데,
주문 페이지에서 현재 테이블에 대한 주문을 띄워줘야합니다.

<img width="305" alt="image" src="https://github.com/BiBimBapClub/bitpay_server/assets/55350092/37d7b880-059d-43ec-8633-b9f1dfcd9c7f">

현재 구조로 개발하게 되면 해당 테이블에 대한 모든 주문 정보, 즉 같은 테이블에 앉았던 이전 사람이 시켰던 주문까지 리스트로 나오게 됩니다.
따라서 Table 에 currentOrderList와 같이, 현재 유효한(고객 입장에서는 내가 이 테이블에 앉아서 시켰던 주문) 주문의 id 값을 지녀야 할 것 같습니다

**Comment by ehdtndla123** [comment]
네 알겠습니다. 고유 id 추가 하면 될 것 같네요.

**Comment by ehdtndla123** [comment]
<img width="336" alt="image" src="https://github.com/BiBimBapClub/bitpay_server/assets/59868624/ddfe4f2c-e4ce-48d7-98ce-0a337a2c0ac7">
uuid 추가하였습니다.
