### ISSUE TITLE
Feat: TableService 에서 Table에 대한 TableHistory 저장 메소드

### ISSUE THREAD

**Issue by ehdtndla123** [BiBimBapClub/bitpay_server#11]
Return : Boolean Type
Parameter : TableDto
Table 을 만들거나 변경할 때 History를 저장해야하는데, 저장할 수 있는 메소드 요청드립니다.

**Comment by kangCoder** [comment]
Parameter 추가: TableDto, String type
type: TIME, STATUS

**Comment by ehdtndla123** [comment]
TableHistoryServiceImpl
 @Override
    public boolean createTableHistory(TableDto tableDto, String type) {
        String tableNumber = tableDto.getNumber();

        //description에 들어가야 하는 것: table 상태 변경 내용, table 이용 시간 추가
        StringBuilder description = new StringBuilder();

        if (type.equals("TIME")) {

        } else if (type.equals("STATUS")) {

        }
        return false;
    }
String으로 변경부탁드립니다.
