### ISSUE TITLE
Feat: Order에서 TableHistory로 주문 기록 넘겨주기 요청

### ISSUE THREAD

**Issue by kangCoder** [BiBimBapClub/bitpay_server#2]
Order 측에서 주문을 완료할 때, 주문 요청에 해당하는 dto를 요청합니다.

주문 기록을 저장하기 위해서 tableNumber, table_history_description을 Order domain에서 가져와야 합니다. 때문에 테이블 번호와 주문 상세에 대한 dto를 반환하는 로직을 Order에 추가해줬으면 합니다.

예를 들어서, 8번 테이블에서 오뎅탕 2개, 쏘야 1개를 시켰다고 하면 dto에서 8, "오뎅탕 2개, 쏘야 1개", 총 가격을 담은 dto가 담고 있으면 합니다.

**Comment by anjm1020** [comment]
재요청으로 Order에 create나 update가 발생할 때, tableHistoryService의 메소드를 호출하여 테이블 히스토리를 저장하는 형태로 구현하는게 유리할 것 같습니다.
따라서 tableHistoryService interface에 Order 엔티티를 인자로 받아 히스토리 생성을 보장하는 메소드 생성을 요청드립니다!
```java
boolean createOrderHistory(Order order);
```

**Comment by kangCoder** [comment]
그럼 TableHistory에서 Order를 요청하는게 아니라 반대쪽으로 가는게 더 낫다는거죠?

그렇게 구현하겠습니다~
