### ISSUE TITLE
Feat: TableRedisRepository에서 table 상태를 변경하는 메서드 생성 요청

### ISSUE THREAD

**Issue by kangCoder** [BiBimBapClub/bitpay_server#4]
TableHistoryService에서 Order가 들어오면 해당 Order에 대해서 TableHistory를 생성하고, Order에 따른 Table의 상태를 변경해줘야 합니다.

TableRedisRepository에서 Table의 상태를 변경하는 메서드 생성 요청 부탁드립니다.

**Comment by ehdtndla123** [comment]
updateTableStatus(Integer tableNumber, String newStatus) 메소드가 존재합니다.
getTable(Integer tableNumber) 로 Table 정보 가져올 수 있습니다.
